# Eleventy: https://www.11ty.dev/
image: debian/stable
packages:
  - nodejs
  - npm
oauth: pages.sr.ht/PAGES:RW
secrets:
- 7562c2fd-1ce8-4e3a-be2b-8ede538f9bfa
sources:
- git@git.sr.ht:~emceeaich/adventures-in-renaming-11ty
environment:
  site: adventuresinrenaming.net
  repo: adventures-in-renaming-11ty
  # Disable npm progress bar
  # https://docs.npmjs.com/cli/v9/using-npm/config#progress
  npm_config_progress: "false"
tasks:
- install: |
    cd $repo
    npm install
- package: |
    cd $repo
    npx eleventy
    tar -C _site -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
